pipeline {
    agent any
    stages {
        
        stage('git') {
            steps {
                git branch: 'main', url: 'https://github.com/houssembenali/TP_CICD.git'
            }
        }
        
        stage('Docker Build Image') {
            steps {
                sh 'docker build -t houssembenali/tp-cicd-ib .'
            }
        }
        
        stage('Docker run') {
            steps {
                sh 'docker run -d --name tp_cicd_container -p 3000:3000 --rm houssembenali/tp-cicd-ib'
            }
        }
        
        stage('Test Container and stop') {
            steps {
                sh 'sleep 3'
                sh 'curl http://192.168.1.223:3000'
                sh 'sleep 3'
                sh 'docker stop tp_cicd_container'
            }
        }
        
        stage('push') {
            steps {
                sh 'docker login -u houssembenali -p MOTDEPASSE'
                sh 'docker push houssembenali/tp-cicd-ib'
            }
        }
    }
}